### ISSUE TITLE
importer simultaneously importing a large number of data files causes one layer to exit

### ISSUE THREAD

**Issue by dbacyj** [vesoft-inc/nebula-importer#219]
A total of more than 500 files，The error is as follows：
![image](https://user-images.githubusercontent.com/72034305/202601458-f60f62ee-680f-44e7-9efd-570d2f2a0a0a.png)

**Comment by yixinglu** [comment]
seems related to https://github.com/vesoft-inc/nebula-importer/issues/95

@veezhang could you help to debug this?

**Comment by veezhang** [comment]
> seems related to #95
> 
> @veezhang could you help to debug this?

👌

**Comment by veezhang** [comment]
```
panic: send on closed channel

goroutine 241 [running]:
github.com/vesoft-inc/nebula-importer/pkg/reader.(*Batch).requestClient(0x400071a200)
        /home/runner/work/nebula-importer/nebula-importer/pkg/reader/batch.go:66 +0x128
github.com/vesoft-inc/nebula-importer/pkg/reader.(*Batch).Add(0x400071a200, 0x1, 0x40b0caeb60, 0x2, 0x2, 0x25)
        /home/runner/work/nebula-importer/nebula-importer/pkg/reader/batch.go:36 +0xc8
github.com/vesoft-inc/nebula-importer/pkg/reader.(*FileReader).Read(0x40001bc050, 0x0, 0x0, 0x0)
        /home/runner/work/nebula-importer/nebula-importer/pkg/reader/reader.go:166 +0x504
github.com/vesoft-inc/nebula-importer/pkg/cmd.(*Runner).Run.func2(0x40002998f0, 0x4000331080, 0x40001bc050, 0x40002001b0, 0x26)
        /home/runner/work/nebula-importer/nebula-importer/pkg/cmd/runner.go:74 +0x28
created by github.com/vesoft-inc/nebula-importer/pkg/cmd.(*Runner).Run
        /home/runner/work/nebula-importer/nebula-importer/pkg/cmd/runner.go:73 +0x5bc
```
