### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by mbande** [vesoft-inc/nebula-importer#92]
trying to run importer in the same machine as nebula, with this command:
```
$ docker run --rm -ti --network=host -v /opt/nebula/import.yaml:/data/import.yaml -v ~/:/data/ vesoft/nebula-importer --config /data/import.yaml
```
i get the following error:
```
2020/10/04 11:53:18 --- START OF NEBULA IMPORTER ---
2020/10/04 11:53:18 [INFO] config.go:399: files[1].schema.vertex is nil
2020/10/04 11:53:29 dial tcp 172.29.3.1:3699: i/o timeout
2020/10/04 11:53:30 --- END OF NEBULA IMPORTER ---
```
also, trying to use external domain name as nebula connection address, i get the following error:
```
2020/10/04 11:57:45 --- START OF NEBULA IMPORTER ---
2020/10/04 11:57:45 [INFO] config.go:399: files[1].schema.vertex is nil
2020/10/04 11:57:45 [INFO] clientmgr.go:28: Create 2 Nebula Graph clients
2020/10/04 11:57:45 [INFO] reader.go:64: Start to read file(0): /data/users_profile.csv, schema: < :VID,user.username:string >
panic: send on closed channel

goroutine 24 [running]:
github.com/vesoft-inc/nebula-importer/pkg/reader.(*Batch).requestClient(0xc000232180)
	/home/nebula-importer/pkg/reader/batch.go:66 +0x14c
github.com/vesoft-inc/nebula-importer/pkg/reader.(*Batch).Add(0xc000232180, 0x1, 0xc00000ec40, 0x2, 0x2)
	/home/nebula-importer/pkg/reader/batch.go:36 +0xa0
github.com/vesoft-inc/nebula-importer/pkg/reader.(*FileReader).Read(0xc0002320c0, 0x0, 0x0)
	/home/nebula-importer/pkg/reader/reader.go:162 +0x570
github.com/vesoft-inc/nebula-importer/pkg/cmd.(*Runner).Run.func2(0xc000014a40, 0xc000014a80, 0xc0002320c0, 0xc000019480, 0x17)
	/home/nebula-importer/pkg/cmd/cmd.go:70 +0x40
created by github.com/vesoft-inc/nebula-importer/pkg/cmd.(*Runner).Run
	/home/nebula-importer/pkg/cmd/cmd.go:69 +0x705
```

PS: i can connect to server with Nebula Graph Studio with no problem, but as the file sizes is so big, i can not use it for import

**Comment by yixinglu** [comment]
Hi @mbande 

Sorry to reply so late. If you have any issues later, welcome to raise your problem in [our forum](https://discuss.nebula-graph.io/). 

Your problem seems that you don't configure the `schema.vertex` field for the second file. Could you give your `config.yaml` here ?
